CREATE DATABASE PUB(
  COD_PUB NUMBER(20) PRIMARY KEY NOT NULL,,
NOMBRE VARCHAR2(10) NOT NULL,
LICENCIA_FISCAL VARCHAR2(10) NOT NULL,
DOMICILIO  VARCHAR2(10) NULL,
FECHA_APERTURA TIMESTAMP DEFAULT SYSDATE NOT NULL,
HORARIO TIME NOT NULL,
COD_LOCALIDAD VARCHAR2(10) NOT NULL
);

CREATE DATABASE TITULAR(
  DNI_TITULAR VARCHAR2(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(10) NOT NULL,
DOMICILIOCOD_PUB VARCHAR2(10) NOT NULL
); 

CREATE DATABASE EMPLEADO(
  DNI_EMPLEADO VARCHAR2(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(10) NOT NULL,
DOMICILIO VARCHAR2(10) NOT NULL
); 

CREATE DATABASE EXISTENCIAS(
  COD_ARTICULO VARCHAR2(10) PRIMARY KEY NOT NULL,
NOMBRE VARCHAR2(10) NOT NULL,
CANTIDAD INTEGER (9)
PRECIO NUMBER (9),
COD_PUB VARCHAR2(10) NOT NULL
); 

CREATE DATABASE LOCALIDAD(
  COD_LOCALIDAD INTEGER(9) PRIMARY KEY,
NOMBRE VARCHAR2(10) NOT NULL
);

CREATE DATABASE PUB_EMPLEADO(
  COD_PUB VARCHAR2(10) NOT NULL,
DNI_EMPLEADO VARCHAR2(10) NOT NULL,
FUNCION VARCHAR2(10) PRIMARY KEY CONSTRAINT check_empleado_funcion
              CHECK (FUNCION IN ('CAMARERO','SEGURIDAD',
              'LIMPIEZA')) 
              DISABLE)
); 

ALTER TABLE EXISTENCIAS  
ADD CONSTRAINT CANTIDAD CHECK (CANTIDAD>0);

ALTER TABLE PUB_EMPLEADO
ADD FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB); 

ALTER TABLE PUB_EMPLEADO
ADD FOREIGN KEY (DNI_EMPLEADO) REFERENCES EMPLEADO(DNI_EMPLEADO); 

ALTER TABLE EXISTENCIAS
ADD FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB); 

ALTER TABLE PUB
ADD FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD);

ALTER TABLE PUB
ADD FOREIGN KEY (COD_LOCALIDAD) REFERENCES LOCALIDAD(COD_LOCALIDAD);

ALTER TABLE TITULAR
ADD FOREIGN KEY (COD_PUB) REFERENCES PUB(COD_PUB);




